### ISSUE TITLE
[Question] Adding descriptor to kotlin-jupyter repository

### ISSUE THREAD

**Issue by ileasile** [breandan/kaliningraph#1]
Hello, @breandan! Don't you mind me adding a library descriptor for this library to [common libraries path in kotlin-jupyter repo](https://github.com/Kotlin/kotlin-jupyter/tree/master/libraries)?

**Comment by breandan** [comment]
Thanks for your interest! It's not really stable yet, but I submitted a PR in case others want to try it out. What is the process for updating? Should library authors submit a PR to the kotlin-jupyter repo whenever the version changes?
