### ISSUE TITLE
Publish on mavenCentral/JCenter

### ISSUE THREAD

**Issue by altavir** [breandan/kaliningraph#3]
Jitpack is unreliable so it is hard to use kaliningraph as a transitive dependency. Even github packages would be better. We can host a fork build at https://bintray.com/mipt-npm/kscience if it is acceptable.

**Comment by breandan** [comment]
I have no idea why @jitpack is so unstable, but I have read and experienced similar issues. Considering your near-death experience migrating to Maven Central, I'm somewhat hesitant to make the switch...

**Comment by altavir** [comment]
We actually made it there. I had to buy the domain though. Our primary hosting is JetBrains Space with https://repo.kotlin.link/ as a proxy.

**Comment by breandan** [comment]
Another failure: https://github.com/Kotlin/dokka/issues/2024#issuecomment-879912756

@jitpack I submitted a support ticket [as requested](https://twitter.com/jitpack/status/1386633158918090752?s=20) describing other flaky download issues but never received a reply. Any suggestions?

**Comment by CommanderTvis** [comment]
JCenter 💀

**Comment by breandan** [comment]
I have [started a petition](https://issues.sonatype.org/browse/OSSRH-72947) to access Maven Central. Keep me in your prayers...

* ["Easy" Publishing to Central Repository](https://www.youtube.com/watch?v=P_3yo-oU1To&list=PLVwVfu3wPo66M_bxVIyLdI7bjlhffHUjj)
* https://central.sonatype.org/publish/publish-guide/
* https://docs.gradle.org/current/userguide/publishing_maven.html
* https://github.com/gradle-nexus/publish-plugin#usage
* https://docs.gradle.org/current/userguide/signing_plugin.html
* https://stackoverflow.com/a/48135914/1772342
* https://stackoverflow.com/questions/57921325/gradle-signarchives-unable-to-read-secret-key
* https://central.sonatype.org/publish/requirements/gpg/
