### ISSUE TITLE
Can't compile project under Windows

### ISSUE THREAD

**Issue by ileasile** [breandan/kaliningraph#4]
`:compileKotlin` ends up with:
```
e: error while writing C:\Projects\kaliningraph\build\classes\kotlin\main\ai\hypergraph\kaliningraph\circuits\Ops$*.class (Permission denied)
```

The problem is most likely in identifier name:
![image](https://user-images.githubusercontent.com/20319593/140182260-efde50b5-a02c-44f6-ad24-9dd488b50249.png)

**Comment by breandan** [comment]
Good to know, this should be fixed. In case you're trying to reproduce Kotlin/kotlin-jupyter#342, here is the [specific commit](https://github.com/breandan/kaliningraph/commit/4b6aadf379ec40fe0c7d5de0ee25fa64520e31b3) and associated [logs from the CI build](https://gist.github.com/breandan/e9bd371f94156227bb11536139e50571). Thanks!
